name: Deployment
on:
    push:
        branches: [ "master" ]
        # Publish semver tags as releases.
        tags: [ 'v*.*.*' ]
    pull_request:
        branches: [ "master" ]

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - 
                name: Checkout repository
                uses: actions/checkout@v4
            -
                name: Deploy using Docker Compose
                run: docker compose up -d --build