name: Development Deployment
on:
    push:
        branches: [ "development" ]
        
jobs:
    deployment:
        runs-on: self-hosted
        environment: development
        steps:
            - 
                name: Checkout repository
                uses: actions/checkout@v4
            -
                name: Deploy using Docker Compose
                run: docker compose -f docker-compose.dev.yaml up -d --build
            - 
                name: Remove old images
                run: docker image prune -f