name: Production Deployment
on:
    push:
        branches: [ "master" ]

jobs:
    deployment:
        environment: production
        runs-on: self-hosted
        steps:
            - 
                name: Checkout repository
                uses: actions/checkout@v4
            -
                name: Deploy using Docker Compose
                run: docker compose -f docker-compose.prod.yaml up -d --build
            - 
                name: Remove old images
                run: docker image prune -f